version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3100 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3100:3100"
    depends_on:
      - db
